#!/usr/bin/env bash

set -e -o pipefail

features=()

#if [ "$GITHUB_REF" = "refs/heads/next" ]; then
#    features+=("experimental")
#fi

arguments=()

if [ ${#features[@]} -gt 0 ]; then
    arguments+=("--features")
    arguments+=("${features[*]}")
fi

echo "::set-output name=args::${arguments[*]}"
