[package]
name    = "ksynth"
version = "0.0.0"
authors = ["Will <will@kentik.com>"]
edition = "2018"

[features]
experimental = []

[dependencies]
anyhow        = "1.0.40"
bytes         = "1.0.1"
capnp         = "0.14.0"
env_logger    = "0.8.3"
futures       = "0.3.13"
hex           = "0.4.3"
http          = "0.2.3"
hyper-rustls  = "0.22.1"
libc          = "0.2.90"
log           = "0.4.14"
nix           = "0.19.1"
parking_lot   = "0.11.1"
rand          = "0.8.3"
rustls        = "0.19.0"
ryu           = "1.0.5"
serde_json    = "1.0.64"
signal-hook   = "0.3.7"
tokio-rustls  = "0.22.0"
tower-service = "0.3.1"
webpki        = "0.21.4"
webpki-roots  = "0.21.0"
yaml-rust     = "0.3.5"

[target.'cfg(target_os = "linux")'.dependencies]
capo          = "0.0.1"

[dependencies.clap]
version  = "2.33.3"
features = ["yaml"]

[dependencies.ed25519-compact]
version  = "0.1.9"

[dependencies.hyper]
version  = "0.14.4"
features = ["client"]

[dependencies.itoa]
version  = "0.4.7"
features = ["i128"]

[dependencies.rustls-native-certs]
version  = "0.5.0"

[dependencies.serde]
version  = "1.0.124"
features = ["derive"]

[dependencies.tokio]
version  = "1.3.0"
features = ["net", "rt-multi-thread", "sync", "time"]

[dependencies.tracing]
version  = "0.1.25"
features = ["log"]

[dependencies.trust-dns-client]
version  = "0.20.1"
default-features = false

[dependencies.trust-dns-resolver]
version  = "0.20.1"
features = ["system-config", "tokio-runtime"]
default-features = false

[dependencies.netdiag]
git      = "https://github.com/kentik/netdiag.git"
rev      = "4477fd62"

[dependencies.notary]
git      = "ssh://git@github.com/kentik/notary.git"
features = ["client"]
default-features = false

[dependencies.synapi]
path = "synapi"

[build-dependencies]
capnpc = "0.14.2"
anyhow = "1.0.40"

[build-dependencies.git2]
version  = "0.13.17"
features = []
default-features = false

[profile.release]
debug = true

[profile.release.package."*"]
debug = false
