[package]
name    = "ksynth"
version = "0.0.0"
authors = ["Will <will@kentik.com>"]
edition = "2018"

[features]
experimental = []

[dependencies]
anyhow        = "1.0.33"
bytes         = "0.5.6"
capnp         = "0.13.4"
env_logger    = "0.7.1"
futures       = "0.3.6"
hex           = "0.4.2"
http          = "0.2.1"
hyper         = "0.13.8"
hyper-rustls  = "0.21.0"
libc          = "0.2.79"
log           = "0.4.11"
nix           = "0.18.0"
parking_lot   = "0.11.0"
rand          = "0.7.3"
rustls        = "0.18.1"
serde_json    = "1.0.58"
signal-hook   = "0.1.16"
socket2       = "0.3.15"
tokio-rustls  = "0.14.1"
tower-service = "0.3.0"
webpki        = "0.21.3"
webpki-roots  = "0.20.0"
yaml-rust     = "0.3.5"

[target.'cfg(target_os = "linux")'.dependencies]
capo          = "0.0.1"

[dependencies.clap]
version  = "2.33.3"
features = ["yaml"]

[dependencies.ed25519-compact]
version  = "0.1.8"

[dependencies.rustls-native-certs]
version  = "0.4.0"

[dependencies.serde]
version  = "1.0.116"
features = ["derive"]

[dependencies.tokio]
version  = "0.2.22"
features = ["rt-threaded", "net"]

[dependencies.trust-dns-client]
version  = "0.19.6"
default-features = false

[dependencies.trust-dns-resolver]
version  = "0.19.6"
features = ["system-config", "tokio-runtime"]
default-features = false

[dependencies.trust-dns-proto]
version  = "0.19.6"
default-features = false

[dependencies.netdiag]
path = "netdiag"

[dependencies.notary]
path = "notary"

[dependencies.synapi]
path = "synapi"

[build-dependencies]
capnpc = "0.13.1"
anyhow = "1.0.33"

[build-dependencies.git2]
version  = "0.13.11"
features = []
default-features = false

[profile.release]
debug = true

[profile.release.package."*"]
debug = false
