[package]
name    = "ksynth"
version = "0.0.0"
authors = ["Will <will@kentik.com>"]
edition = "2018"

[dependencies]
anyhow        = "1.0.31"
bytes         = "0.5.4"
capnp         = "0.12.3"
env_logger    = "0.7.1"
futures       = "0.3.5"
hex           = "0.4.2"
libc          = "0.2.71"
log           = "0.4.8"
nix           = "0.18.0"
parking_lot   = "0.11.0"
rand          = "0.7.3"
signal-hook   = "0.1.15"
serde_json    = "1.0.55"
yaml-rust     = "0.3.5"

[target.'cfg(target_os = "linux")'.dependencies]
capo          = "0.0.1"

[dependencies.clap]
version  = "2.33.1"
features = ["yaml"]

[dependencies.ed25519-compact]
version  = "0.1.6"

[dependencies.reqwest]
version  = "0.10.4"
features = ["gzip", "rustls-tls"]
default-features = false

[dependencies.serde]
version  = "1.0.112"
features = ["derive"]

[dependencies.tokio]
version  = "0.2.22"
features = ["rt-threaded", "net"]

[dependencies.trust-dns-resolver]
version  = "0.19.5"

[dependencies.netdiag]
path = "netdiag"

[dependencies.notary]
path = "notary"

[dependencies.synapi]
path = "synapi"

[build-dependencies]
capnpc = "0.12.3"
anyhow = "1.0.31"

[build-dependencies.git2]
version  = "0.13.6"
features = []
default-features = false

[profile.release]
debug = true

[profile.release.package."*"]
debug = false