[package]
name    = "ksynth"
version = "0.0.0"
authors = ["Will <will@kentik.com>"]
edition = "2018"

[features]
experimental = []

[dependencies]
anyhow        = "1.0.37"
bytes         = "1.0.0"
capnp         = "0.14.0"
env_logger    = "0.8.2"
futures       = "0.3.8"
hex           = "0.4.2"
http          = "0.2.2"
hyper-rustls  = "0.22.1"
libc          = "0.2.81"
log           = "0.4.11"
nix           = "0.19.1"
parking_lot   = "0.11.1"
rand          = "0.8.1"
rustls        = "0.19.0"
serde_json    = "1.0.61"
signal-hook   = "0.3.2"
tokio-rustls  = "0.22.0"
tower-service = "0.3.0"
webpki        = "0.21.4"
webpki-roots  = "0.21.0"
yaml-rust     = "0.3.5"

[target.'cfg(target_os = "linux")'.dependencies]
capo          = "0.0.1"

[dependencies.clap]
version  = "2.33.3"
features = ["yaml"]

[dependencies.ed25519-compact]
version  = "0.1.9"

[dependencies.hyper]
version  = "0.14.2"
features = ["client"]

[dependencies.rustls-native-certs]
version  = "0.5.0"

[dependencies.serde]
version  = "1.0.118"
features = ["derive"]

[dependencies.tokio]
version  = "1.0.1"
features = ["net", "rt-multi-thread", "sync", "time"]

[dependencies.trust-dns-client]
version  = "0.20.0"
default-features = false

[dependencies.trust-dns-resolver]
version  = "0.20.0"
features = ["system-config", "tokio-runtime"]
default-features = false

[dependencies.netdiag]
path = "netdiag"

[dependencies.notary]
path = "notary"

[dependencies.synapi]
path = "synapi"

[build-dependencies]
capnpc = "0.14.2"
anyhow = "1.0.37"

[build-dependencies.git2]
version  = "0.13.15"
features = []
default-features = false

[profile.release]
debug = true

[profile.release.package."*"]
debug = false
