meta:
  description: Kentik Synthetic Agent
  vendor: Kentik
  maintainer: Kentik
files:
  "/opt/kentik/ksynth/ksynth":
    file: ksynth
    mode: "0755"
  "/etc/default/ksynth":
    file: pkg/etc/default/ksynth
    mode: "0644"
    keep: true
dirs:
  - /opt/kentik/ksynth
  - /var/lib/ksynth
units:
  - pkg/etc/systemd/system/ksynth.service
scripts:
  "post-install": pkg/scripts/post-install
conditional:
  - when: format == "deb"
    units:
      - pkg/etc/systemd/system/ksynth-update-deb.service
      - pkg/etc/systemd/system/ksynth-update-deb.timer
  - when: format == "rpm"
    units:
      - pkg/etc/systemd/system/ksynth-update-rpm.service
      - pkg/etc/systemd/system/ksynth-update-rpm.timer
user: ksynth
