meta:
  description: Kentik Synthetic Agent
  vendor: Kentik
  maintainer: Kentik
files:
  "/opt/kentik/ksynth/ksynth":
    file: ksynth
    mode: "0755"
    user: ksynth
  "/etc/default/ksynth":
    file: pkg/etc/default/ksynth
    mode: "0644"
    keep: true
dirs:
  - /opt/kentik/ksynth
  - /var/lib/ksynth
units:
  - pkg/etc/systemd/system/ksynth.service
scripts:
  "post-install": pkg/scripts/post-install
user: ksynth
