[target.aarch64-unknown-linux-musl]
rustflags = [
  "-C", "link-arg=-Wl,-Bstatic",
  "-C", "link-arg=-lstdc++",
  "-C", "link-arg=-Wl,-Bstatic",
  "-C", "link-arg=-lc",
]

[target.armv7-unknown-linux-musleabihf]
rustflags = [
  "-C", "link-arg=-Wl,-Bstatic",
  "-C", "link-arg=-lstdc++",
  "-C", "link-arg=-Wl,-Bstatic",
  "-C", "link-arg=-lc",
  "-C", "link-arg=-Wl,-Bstatic",
  "-C", "link-arg=-lgcc",
]

[target.x86_64-unknown-linux-musl]
rustflags = [
  "-C", "link-arg=-Wl,-Bstatic",
  "-C", "link-arg=-lstdc++",
  "-C", "link-arg=-Wl,-Bstatic",
  "-C", "link-arg=-lc",
]
