name: build

on:
  push:
    branches: "*"
    tags: "[0-9]+.[0-9]+.[0-9]+*"

jobs:
  build:
    runs-on: ${{ matrix.builder }}
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            builder: ubuntu-latest
            cross: true
          # FIXME: uncomment
          # - target: x86_64-apple-darwin
          #   builder: macos-latest
          #   cross: false
          - target: aarch64-unknown-linux-musl
            builder: ubuntu-latest
            cross: true
          - target: armv7-unknown-linux-musleabihf
            builder: ubuntu-latest
            cross: true
    continue-on-error: ${{ startsWith(matrix.builder, 'macos') }}
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: beta
          target: ${{ matrix.target }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: docker/build-push-action@v2
        with:
          context: .github/workflows
          file: .github/workflows/Dockerfile.${{ matrix.target }}
          tags: local/cross:${{ matrix.target }}
          push: false
        if: ${{ matrix.cross }}
      - run: brew install capnp
        if: ${{ startsWith(matrix.builder, 'macos') }}
      - id: cargo-args
        run: .github/scripts/cargo-args
      - uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.cross }}
          command: build
          args: --release --target ${{ matrix.target }} ${{ steps.cargo-args.outputs.args }}
      - uses: actions/upload-artifact@v2
        with:
          name: ksynth-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/ksynth

  artifacts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
          - armv7-unknown-linux-musleabihf
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - uses: actions/download-artifact@v2
        with:
          name: ksynth-${{ matrix.target }}
      - run: |
          aws s3 cp ksynth $BUCKET/ksynth-${{ matrix.target }}
    needs: build

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: docker/setup-buildx-action@v1
      - uses: docker/setup-qemu-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - uses: actions/download-artifact@v2
        with:
          name: ksynth-aarch64-unknown-linux-musl
          path: binary/arm64
      - uses: actions/download-artifact@v2
        with:
          name: ksynth-armv7-unknown-linux-musleabihf
          path: binary/armv7
      - uses: actions/download-artifact@v2
        with:
          name: ksynth-x86_64-unknown-linux-musl
          path: binary/amd64
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          tags: ${{ github.repository }}:${{ github.sha }}
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
    needs: build

  release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: create
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: ${{ contains(github.ref, '-rc') }}
          body_path: .github/release-body.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    needs: build
    if: startsWith(github.ref, 'refs/tags')

  assets:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
          - armv7-unknown-linux-musleabihf
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: ksynth-${{ matrix.target }}
      - run: "file *"
      - uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ksynth
          asset_name: ksynth-${{ matrix.target }}
          asset_content_type: application/binary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    needs: release

env:
  BUCKET: s3://kentik-github-actions/${{ github.repository }}/${{ github.sha }}
