name: release

on:
  release:
    types: [edited]

jobs:
  control:
    runs-on: ubuntu-latest
    outputs:
      actions: ${{ steps.control.outputs.actions }}
    steps:
      - id: control
        uses: kentik/actions/control@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release-update:
    runs-on: ubuntu-latest
    steps:
      - uses: kentik/actions/notary/release@master
        with:
          name: ${{ github.event.repository.name }}
          version: ${{ github.event.release.tag_name }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-2
    needs: control
    if: contains(needs.control.outputs.actions, 'release-update')
