FROM docker.io/rustembedded/cross:x86_64-unknown-freebsd

RUN curl --retry 3 -sSfL http://ftp.freebsd.org/pub/FreeBSD/releases/amd64/12.1-RELEASE/base.txz | tar xJvf - -C /usr/local/x86_64-unknown-freebsd12/lib --strip-components 3 ./usr/lib/libkvm.a ./usr/lib/libdevstat.a

RUN apt-get update && apt-get install -y capnproto
