name: publish

on:
  release:
    types: [published]

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - id: version
        run: |
          aws s3 cp $BUCKET/ksynth-x86_64-unknown-linux-musl ksynth
          chmod u+x ksynth
          VERSION=$(./ksynth -V | cut -d ' ' -f 2)
          echo ::set-output name=version::$VERSION

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - run: |
          aws s3 cp $BUCKET/ksynth-aarch64-unknown-linux-musl     binary/arm64/ksynth
          aws s3 cp $BUCKET/ksynth-armv7-unknown-linux-musleabihf binary/armv7/ksynth
          aws s3 cp $BUCKET/ksynth-x86_64-unknown-linux-musl      binary/amd64/ksynth
      - uses: docker/setup-buildx-action@v1
      - uses: docker/setup-qemu-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          tags: ${{ github.repository }}:${{ needs.version.outputs.version }}
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          tags: ${{ github.repository }}:latest
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
        if: github.event.release.prerelease == false
    needs: version

  notarize:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            arch: x86_64
          - target: aarch64-unknown-linux-musl
            arch: aarch64
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - run: |
          aws s3 cp $BUCKET/ksynth-${{ matrix.target }} ksynth
      - uses: kentik/actions/notary/submit@master
        with:
          name: ${{ github.event.repository.name }}
          version: ${{ needs.version.outputs.version }}
          arch: ${{ matrix.arch  }}
          system: linux
          artifact: /github/workspace/ksynth
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-2
    needs: version
    if: github.event.release.prerelease == false

  package:
    runs-on: ubuntu-latest
    outputs:
      package-deb: ${{ steps.package-deb.outputs.package }}
      package-rpm: ${{ steps.package-rpm.outputs.package }}
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            arch: x86_64
          - target: armv7-unknown-linux-musleabihf
            arch: armv7
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - run: |
          aws s3 cp $BUCKET/ksynth-${{ matrix.target }} ksynth
      - id: package-deb
        uses: kentik/pkg@master
        with:
          name: ${{ github.event.repository.name }}
          version: ${{ needs.version.outputs.version }}
          arch: ${{ matrix.arch }}
          format: deb
          package: package.yml
      - id: package-rpm
        uses: kentik/pkg@master
        with:
          name: ${{ github.event.repository.name }}
          version: ${{ needs.version.outputs.version }}
          arch: ${{ matrix.arch }}
          format: rpm
          package: package.yml
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.package-deb.outputs.package }}
          path: ${{ steps.package-deb.outputs.package }}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.package-rpm.outputs.package }}
          path: ${{ steps.package-rpm.outputs.package }}
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - run: |
          gem install package_cloud
      - name: publish
        run: |
          case "${{ github.event.release.prerelease }}" in
                  true) REPO="ksynth-dev" ;;
                 false) REPO="ksynth"     ;;
          esac

          package_cloud push kentik/$REPO/debian/jessie  $DEB
          package_cloud push kentik/$REPO/debian/stretch $DEB
          package_cloud push kentik/$REPO/debian/buster  $DEB

          package_cloud push kentik/$REPO/ubuntu/focal   $DEB
          package_cloud push kentik/$REPO/ubuntu/bionic  $DEB

          package_cloud push kentik/$REPO/el/7 $RPM
          package_cloud push kentik/$REPO/el/8 $RPM
        env:
          DEB: ${{ steps.package-deb.outputs.package }}
          RPM: ${{ steps.package-rpm.outputs.package }}
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
    needs: version

env:
  BUCKET: s3://kentik-github-actions/${{ github.repository }}/${{ github.sha }}
