name: vacuum

on:
  workflow_dispatch:
    inputs:
      expire:
        description: 'max age'
        required: true
        default: '2d'

jobs:
  artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: ${{ github.event.inputs.expire }}
